eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@10.0.0.2:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: zuul-server
zuul:
  routes:
    say-hello-service:
      path: /say-hello-service/**
      serviceId: say-hello-service
    greeting:
      path: /greating-service/**
      serviceId: config-client